### ISSUE TITLE
redis error

### ISSUE THREAD

**Issue by itsviiruz** [91DarioDev/TopSupergroupsBot#97]
Non riesco a connettermi a redis: 

conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: FATALE:  autenticazione con password fallita per l'utente "user00"

**Comment by 91DarioDev** [comment]
A vedere così mi sembra un errore di postgres e in particolare che non ti stai autenticando bene a postgres e ti sta dicendo che la password è sbagliata
